package org.synechron.petstay.model;
// Generated Jul 31, 2017 4:06:11 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bookingtype generated by hbm2java
 */
@Entity
@Table(name = "bookingtype", catalog = "petdb")
public class Bookingtype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idbookingType;
	private String bookingTypeName;
	private Set<Booking> bookings = new HashSet<Booking>();

	public Bookingtype() {
	}

	public Bookingtype(String bookingTypeName, Set<Booking> bookings) {
		this.bookingTypeName = bookingTypeName;
		this.bookings = bookings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idbookingType", unique = true, nullable = false)
	public Integer getIdbookingType() {
		return this.idbookingType;
	}

	public void setIdbookingType(Integer idbookingType) {
		this.idbookingType = idbookingType;
	}

	@Column(name = "bookingTypeName", length = 45)
	public String getBookingTypeName() {
		return this.bookingTypeName;
	}

	public void setBookingTypeName(String bookingTypeName) {
		this.bookingTypeName = bookingTypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookingtype")
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
