package org.synechron.petstay.model;
// Generated Jul 31, 2017 4:06:11 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cab generated by hbm2java
 */
@Entity
@Table(name = "cab", catalog = "petdb")
public class Cab implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cid;
	private Booking booking;
	private int cdriverContact;
	private String chomeAddress;
	private String cmodel;
	private String cowner;
	private String currentLocation;
	private boolean isAvailable;

	public Cab() {
	}

	public Cab(int cdriverContact, boolean isAvailable) {
		this.cdriverContact = cdriverContact;
		this.isAvailable = isAvailable;
	}

	public Cab(Booking booking, int cdriverContact, String chomeAddress, String cmodel, String cowner,
			String currentLocation, boolean isAvailable) {
		this.booking = booking;
		this.cdriverContact = cdriverContact;
		this.chomeAddress = chomeAddress;
		this.cmodel = cmodel;
		this.cowner = cowner;
		this.currentLocation = currentLocation;
		this.isAvailable = isAvailable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cID", unique = true, nullable = false)
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookingcabId")
	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	@Column(name = "cDriverContact", nullable = false)
	public int getCdriverContact() {
		return this.cdriverContact;
	}

	public void setCdriverContact(int cdriverContact) {
		this.cdriverContact = cdriverContact;
	}

	@Column(name = "cHomeAddress")
	public String getChomeAddress() {
		return this.chomeAddress;
	}

	public void setChomeAddress(String chomeAddress) {
		this.chomeAddress = chomeAddress;
	}

	@Column(name = "cModel")
	public String getCmodel() {
		return this.cmodel;
	}

	public void setCmodel(String cmodel) {
		this.cmodel = cmodel;
	}

	@Column(name = "cOwner")
	public String getCowner() {
		return this.cowner;
	}

	public void setCowner(String cowner) {
		this.cowner = cowner;
	}

	@Column(name = "currentLocation")
	public String getCurrentLocation() {
		return this.currentLocation;
	}

	public void setCurrentLocation(String currentLocation) {
		this.currentLocation = currentLocation;
	}

	@Column(name = "isAvailable", nullable = false)
	public boolean isIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

}
