package org.synechron.petstay.model;
// Generated Jul 31, 2017 4:06:11 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Dog generated by hbm2java
 */
@Entity
@Table(name = "dog", catalog = "petdb")
public class Dog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer did;
	private Integer dage;
	private String dbreed;
	private String dname;
	private Float dweight;
	private String downerAddress;
	private String downerEmailId;
	private Long downerMobile;
	private String downerName;
	private Set<Booking> bookings = new HashSet<Booking>();

	public Dog() {
	}

	public Dog(Integer dage, String dbreed, String dname, Float dweight, String downerAddress, String downerEmailId,
			Long downerMobile, String downerName, Set<Booking> bookings) {
		this.dage = dage;
		this.dbreed = dbreed;
		this.dname = dname;
		this.dweight = dweight;
		this.downerAddress = downerAddress;
		this.downerEmailId = downerEmailId;
		this.downerMobile = downerMobile;
		this.downerName = downerName;
		this.bookings = bookings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "dID", unique = true, nullable = false)
	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	@Column(name = "dAge")
	public Integer getDage() {
		return this.dage;
	}

	public void setDage(Integer dage) {
		this.dage = dage;
	}

	@Column(name = "dBreed")
	public String getDbreed() {
		return this.dbreed;
	}

	public void setDbreed(String dbreed) {
		this.dbreed = dbreed;
	}

	@Column(name = "dName")
	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	@Column(name = "dWeight", precision = 12, scale = 0)
	public Float getDweight() {
		return this.dweight;
	}

	public void setDweight(Float dweight) {
		this.dweight = dweight;
	}

	@Column(name = "dOwnerAddress")
	public String getDownerAddress() {
		return this.downerAddress;
	}

	public void setDownerAddress(String downerAddress) {
		this.downerAddress = downerAddress;
	}

	@Column(name = "dOwnerEmailId")
	public String getDownerEmailId() {
		return this.downerEmailId;
	}

	public void setDownerEmailId(String downerEmailId) {
		this.downerEmailId = downerEmailId;
	}

	@Column(name = "dOwnerMobile")
	public Long getDownerMobile() {
		return this.downerMobile;
	}

	public void setDownerMobile(Long downerMobile) {
		this.downerMobile = downerMobile;
	}

	@Column(name = "dOwnerName")
	public String getDownerName() {
		return this.downerName;
	}

	public void setDownerName(String downerName) {
		this.downerName = downerName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dog")
	@JsonIgnore
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
