package org.synechron.petstay.model;
// Generated Jul 31, 2017 4:06:11 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.synechron.utility.Amenities;
import org.synechron.utility.StayType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Home generated by hbm2java
 */
@Entity
@Table(name = "home", catalog = "petdb")
public class Home implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer hid;
	private Booking booking;
	private Amenities amenities;
	private int cost;
	private String haddress;
	private Integer hcontact;
	private boolean isAvailable;
	private int noofRooms;
	private int rating;
	private StayType stayType;

	public Home() {
	}

	public Home(int cost, boolean isAvailable, int noofRooms, int rating) {
		this.cost = cost;
		this.isAvailable = isAvailable;
		this.noofRooms = noofRooms;
		this.rating = rating;
	}

	public Home(Booking booking, Amenities amenities, int cost, String haddress, Integer hcontact, boolean isAvailable,
			int noofRooms, int rating, StayType stayType) {
		this.booking = booking;
		this.amenities = amenities;
		this.cost = cost;
		this.haddress = haddress;
		this.hcontact = hcontact;
		this.isAvailable = isAvailable;
		this.noofRooms = noofRooms;
		this.rating = rating;
		this.stayType = stayType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "hID", unique = true, nullable = false)
	public Integer getHid() {
		return this.hid;
	}

	public void setHid(Integer hid) {
		this.hid = hid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookingId")
	@JsonIgnore
	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	@Column(name = "amenities")
	public Amenities getAmenities() {
		return this.amenities;
	}

	public void setAmenities(Amenities amenities) {
		this.amenities = amenities;
	}

	@Column(name = "cost", nullable = false)
	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	@Column(name = "hAddress")
	public String getHaddress() {
		return this.haddress;
	}

	public void setHaddress(String haddress) {
		this.haddress = haddress;
	}

	@Column(name = "hContact")
	public Integer getHcontact() {
		return this.hcontact;
	}

	public void setHcontact(Integer hcontact) {
		this.hcontact = hcontact;
	}

	@Column(name = "isAvailable", nullable = false)
	public boolean isIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

	@Column(name = "noofRooms", nullable = false)
	public int getNoofRooms() {
		return this.noofRooms;
	}

	public void setNoofRooms(int noofRooms) {
		this.noofRooms = noofRooms;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "stayType")
	public StayType getStayType() {
		return this.stayType;
	}

	public void setStayType(StayType stayType) {
		this.stayType = stayType;
	}

}
